#!/usr/bin/env python3
"""Fix remaining JavaScript syntax issues in manager dashboard"""

import re

def fix_remaining_issues():
    with open('templates/manager/dashboard.html', 'r') as f:
        content = f.read()
    
    # Fix missing closing braces and semicolons
    fixes = [
        # Fix missing closing braces in functions
        (r'closeBulkActionModal\(\) \{[\s\S]*?currentBulkActionType = null;', 'closeBulkActionModal() {\n    const modal = document.getElementById(\'bulkActionModal\');\n    modal.classList.add(\'hidden\');\n    currentBulkAction = null;\n    currentBulkActionType = null;\n}'),
        
        # Fix missing closing braces in confirmBulkAction
        (r'confirmBulkAction\(\) \{[\s\S]*?closeBulkActionModal\(\);', 'confirmBulkAction() {\n    const selected = document.querySelectorAll(\'.select-item:checked\');\n    const selectedIds = Array.from(selected).map(cb => cb.dataset.id);\n    const selectedNames = Array.from(selected).map(cb => cb.dataset.name);\n    if (currentBulkAction === \'move\') {\n        performBulkMove(selectedIds, selectedNames, currentBulkActionType);\n    } else if (currentBulkAction === \'reassign\') {\n        performBulkReassign(selectedIds, selectedNames);\n    }\n    closeBulkActionModal();\n}'),
        
        # Fix missing closing braces in performBulkMove
        (r'performBulkMove\(ids, names, status\) \{[\s\S]*?showNotification\(`Successfully moved', 'performBulkMove(ids, names, status) {\n    fetch(\'/manager/bulk_move_candidates\', {\n        method: \'POST\',\n        headers: {\n            \'Content-Type\': \'application/json\',\n        },\n        body: JSON.stringify({\n            candidate_ids: ids,\n            status: status\n        })\n    })\n    .then(response => response.json())\n    .then(data => {\n        if (data.success) {\n            showNotification(`Successfully moved'),
        
        # Fix missing closing braces in performBulkReassign
        (r'performBulkReassign\(ids, names\) \{[\s\S]*?showNotification\(`Successfully reassigned', 'performBulkReassign(ids, names) {\n    fetch(\'/manager/bulk_reassign_candidates\', {\n        method: \'POST\',\n        headers: {\n            \'Content-Type\': \'application/json\',\n        },\n        body: JSON.stringify({\n            candidate_ids: ids\n        })\n    })\n    .then(response => response.json())\n    .then(data => {\n        if (data.success) {\n            showNotification(`Successfully reassigned'),
        
        # Fix missing closing braces in showNotification
        (r'showNotification\(message, type\) \{[\s\S]*?setTimeout\(\(\) => \{[\s\S]*?notification\.remove\(\);[\s\S]*?3000\);', 'showNotification(message, type) {\n    const notification = document.createElement(\'div\');\n    notification.className = `fixed top-4 right-4 px-6 py-3 rounded-lg shadow-lg z-50 ${\n        type === \'success\' ? \'bg-green-500 text-white\' : \'bg-red-500 text-white\'\n    }`;\n    notification.textContent = message;\n    document.body.appendChild(notification);\n    setTimeout(() => {\n        notification.remove();\n    }, 3000);\n}'),
        
        # Fix missing closing braces in initializeManagerStarRatings
        (r'initializeManagerStarRatings\(\) \{[\s\S]*?highlightStars\(ratingContainer, rating\);[\s\S]*?});[\s\S]*?});[\s\S]*?});', 'initializeManagerStarRatings() {\n    const starRatings = document.querySelectorAll(\'.star-rating\');\n    starRatings.forEach(ratingContainer => {\n        const stars = ratingContainer.querySelectorAll(\'.star\');\n        const fieldName = ratingContainer.dataset.field;\n        stars.forEach(star => {\n            star.addEventListener(\'click\', function() {\n                const rating = parseInt(this.dataset.rating);\n                setRating(ratingContainer, rating, fieldName);\n            });\n            star.addEventListener(\'mouseenter\', function() {\n                const rating = parseInt(this.dataset.rating);\n                highlightStars(ratingContainer, rating);\n            });\n            star.addEventListener(\'mouseleave\', function() {\n                const rating = parseInt(ratingContainer.dataset.currentRating || 0);\n                highlightStars(ratingContainer, rating);\n            });\n        });\n    });\n}'),
        
        # Fix missing closing braces in setRating
        (r'setRating\(ratingContainer, rating, fieldName\) \{[\s\S]*?console\.log\(`Rating set for', 'setRating(ratingContainer, rating, fieldName) {\n    ratingContainer.dataset.currentRating = rating;\n    const hiddenInput = document.getElementById(fieldName);\n    if (hiddenInput) {\n        hiddenInput.value = rating;\n    }\n    highlightStars(ratingContainer, rating);\n    console.log(`Rating set for'),
        
        # Fix missing closing braces in highlightStars
        (r'highlightStars\(ratingContainer, rating\) \{[\s\S]*?star\.classList\.remove\(\'filled\'\);[\s\S]*?});', 'highlightStars(ratingContainer, rating) {\n    const stars = ratingContainer.querySelectorAll(\'.star\');\n    stars.forEach((star, index) => {\n        const starRating = index + 1;\n        if (starRating <= rating) {\n            star.textContent = \'●\';\n            star.classList.add(\'filled\');\n        } else {\n            star.textContent = \'○\';\n            star.classList.remove(\'filled\');\n        }\n    });\n}'),
        
        # Fix missing closing braces in calculateManagerOverallRating
        (r'calculateManagerOverallRating\(\) \{[\s\S]*?console\.log\(\'Manager overall rating calculated:\', finalScore\);[\s\S]*?return finalScore;', 'calculateManagerOverallRating() {\n    const ratings = {\n        communication: parseInt(document.getElementById(\'communication_skills\')?.value || \'0\'),\n        technical: parseInt(document.getElementById(\'technical_skills\')?.value || \'0\'),\n        problemSolving: parseInt(document.getElementById(\'problem_solving\')?.value || \'0\'),\n        culturalFit: parseInt(document.getElementById(\'cultural_fit\')?.value || \'0\')\n    };\n    const allRated = Object.values(ratings).every(rating => rating > 0);\n    if (!allRated) {\n        document.getElementById(\'manager_overall_rating_display\').textContent = \'--\';\n        document.getElementById(\'manager_overall_rating\').value = \'0\';\n        return;\n    }\n    let overallScore = 0;\n    let totalWeight = 0;\n    overallScore += ratings.communication * 0.25;\n    totalWeight += 0.25;\n    overallScore += ratings.technical * 0.30;\n    totalWeight += 0.30;\n    overallScore += ratings.problemSolving * 0.25;\n    totalWeight += 0.25;\n    overallScore += ratings.culturalFit * 0.20;\n    totalWeight += 0.20;\n    const finalScore = Math.round(overallScore / totalWeight * 10) / 10;\n    const displayElement = document.getElementById(\'manager_overall_rating_display\');\n    const hiddenInput = document.getElementById(\'manager_overall_rating\');\n    if (displayElement && hiddenInput) {\n        displayElement.textContent = finalScore.toFixed(1);\n        hiddenInput.value = finalScore;\n        if (finalScore >= 4.5) {\n            displayElement.className = \'text-3xl font-bold text-green-400 mb-2\';\n        } else if (finalScore >= 3.5) {\n            displayElement.className = \'text-3xl font-bold text-yellow-400 mb-2\';\n        } else {\n            displayElement.className = \'text-3xl font-bold text-red-400 mb-2\';\n        }\n    }\n    console.log(\'Manager overall rating calculated:\', finalScore);\n    return finalScore;\n}'),
        
        # Fix missing closing braces in resetManagerRatings
        (r'resetManagerRatings\(\) \{[\s\S]*?console\.log\(\'Manager ratings reset\');', 'resetManagerRatings() {\n    const starRatings = document.querySelectorAll(\'.star-rating\');\n    const hiddenInputs = [\'communication_skills\', \'technical_skills\', \'problem_solving\', \'cultural_fit\', \'manager_overall_rating\'];\n    starRatings.forEach(ratingContainer => {\n        const stars = ratingContainer.querySelectorAll(\'.star\');\n        stars.forEach(star => {\n            star.textContent = \'○\';\n            star.classList.remove(\'filled\');\n            star.style.color = \'#6b7280\';\n        });\n        ratingContainer.dataset.currentRating = \'0\';\n    });\n    hiddenInputs.forEach(fieldId => {\n        const input = document.getElementById(fieldId);\n        if (input) input.value = \'0\';\n    });\n    const overallDisplay = document.getElementById(\'manager_overall_rating_display\');\n    if (overallDisplay) {\n        overallDisplay.textContent = \'--\';\n        overallDisplay.className = \'text-3xl font-bold text-pink-400 mb-2\';\n    }\n    console.log(\'Manager ratings reset\');\n}'),
        
        # Fix missing closing braces in toggleFeedbackSections
        (r'toggleFeedbackSections\(\) \{[\s\S]*?rejectionReasonsSection\.classList\.remove\(\'hidden\'\);', 'toggleFeedbackSections() {\n    const status = document.getElementById(\'feedbackStatus\').value;\n    const managerRatingSection = document.getElementById(\'managerRatingSection\');\n    const rejectionReasonsSection = document.getElementById(\'rejectionReasonsSection\');\n    managerRatingSection.classList.add(\'hidden\');\n    rejectionReasonsSection.classList.add(\'hidden\');\n    if (status === \'Selected\') {\n        managerRatingSection.classList.remove(\'hidden\');\n    } else if (status === \'Not Selected\') {\n        rejectionReasonsSection.classList.remove(\'hidden\');\n    }\n}'),
        
        # Fix missing closing braces in toggleFeedbackOtherNotes
        (r'toggleFeedbackOtherNotes\(\) \{[\s\S]*?otherNotesField\.style\.display = otherCheckbox\.checked \? \'block\' : \'none\';', 'toggleFeedbackOtherNotes() {\n    const otherCheckbox = document.getElementById(\'feedback_other\');\n    const otherNotesField = document.getElementById(\'feedbackOtherNotesField\');\n    otherNotesField.style.display = otherCheckbox.checked ? \'block\' : \'none\';\n}'),
        
        # Fix missing closing braces in showRejectionReasonsModal
        (r'showRejectionReasonsModal\(candidateId, candidateName\) \{[\s\S]*?document\.getElementById\(\'rejectionReasonsModal\'\)\.classList\.add\(\'flex\'\);', 'showRejectionReasonsModal(candidateId, candidateName) {\n    document.getElementById(\'rejectionCandidateId\').value = candidateId;\n    document.getElementById(\'rejectionCandidateName\').textContent = candidateName;\n    document.getElementById(\'rejectionReasonsModal\').classList.remove(\'hidden\');\n    document.getElementById(\'rejectionReasonsModal\').classList.add(\'flex\');\n}'),
        
        # Fix missing closing braces in hideRejectionReasonsModal
        (r'hideRejectionReasonsModal\(\) \{[\s\S]*?document\.getElementById\(\'otherNotesField\'\)\.style\.display = \'none\';', 'hideRejectionReasonsModal() {\n    document.getElementById(\'rejectionReasonsModal\').classList.add(\'hidden\');\n    document.getElementById(\'rejectionReasonsModal\').classList.remove(\'flex\');\n    document.getElementById(\'rejectionReasonsForm\').reset();\n    document.getElementById(\'otherNotesField\').style.display = \'none\';\n}'),
        
        # Fix missing closing braces in toggleOtherNotes
        (r'toggleOtherNotes\(\) \{[\s\S]*?otherNotesField\.style\.display = otherCheckbox\.checked \? \'block\' : \'none\';', 'toggleOtherNotes() {\n    const otherCheckbox = document.getElementById(\'other\');\n    const otherNotesField = document.getElementById(\'otherNotesField\');\n    otherNotesField.style.display = otherCheckbox.checked ? \'block\' : \'none\';\n}'),
        
        # Fix missing closing braces in saveRejectionReasons
        (r'saveRejectionReasons\(\) \{[\s\S]*?alert\(\'Error saving rejection reasons\. Please try again\.\');[\s\S]*?});', 'saveRejectionReasons() {\n    const candidateId = document.getElementById(\'rejectionCandidateId\').value;\n    const selectedReasons = [];\n    const checkboxes = document.querySelectorAll(\'input[name="rejection_reasons"]:checked\');\n    checkboxes.forEach(checkbox => {\n        if (checkbox.value === \'other\') {\n            const otherNotes = document.getElementById(\'otherNotes\').value.trim();\n            if (otherNotes) {\n                selectedReasons.push(`Other: ${otherNotes}`);\n            }\n        } else {\n            selectedReasons.push(checkbox.value);\n        }\n    });\n    if (selectedReasons.length === 0) {\n        alert(\'Please select at least one reason for rejection.\');\n        return;\n    }\n    fetch(\'/manager/save_rejection_reasons\', {\n        method: \'POST\',\n        headers: {\n            \'Content-Type\': \'application/json\',\n        },\n        body: JSON.stringify({\n            candidate_id: candidateId,\n            rejection_reasons: selectedReasons\n        })\n    })\n    .then(response => response.json())\n    .then(data => {\n        if (data.success) {\n            hideRejectionReasonsModal();\n            location.reload();\n        } else {\n            alert(\'Error saving rejection reasons: \' + data.message);\n        }\n    })\n    .catch(error => {\n        console.error(\'Error:\', error);\n        alert(\'Error saving rejection reasons. Please try again.\');\n    });\n}'),
        
        # Fix missing closing braces in extractManagerCandidateData
        (r'extractManagerCandidateData\(\) \{[\s\S]*?return candidates;', 'extractManagerCandidateData() {\n    const candidates = [];\n    const candidateElements = document.querySelectorAll(\'[data-candidate-id]\');\n    candidateElements.forEach(element => {\n        const candidateId = element.getAttribute(\'data-candidate-id\');\n        const nameElement = element.querySelector(\'.candidate-name, .font-medium\');\n        const statusElement = element.querySelector(\'.status-badge, .px-2\');\n        const hrElement = element.querySelector(\'.hr-info, .text-sm\');\n        const dateElement = element.querySelector(\'.date-info, .text-xs\');\n        if (candidateId && nameElement) {\n            candidates.push({\n                id: candidateId,\n                name: nameElement.textContent.trim(),\n                status: statusElement ? statusElement.textContent.trim() : \'Pending\',\n                hr: hrElement ? hrElement.textContent.trim() : \'Unknown HR\',\n                date: dateElement ? dateElement.textContent.trim() : new Date().toISOString().split(\'T\')[0]\n            });\n        }\n    });\n    return candidates;\n}'),
        
        # Fix missing closing braces in processStatusData
        (r'processStatusData\(candidates\) \{[\s\S]*?return statusCounts;', 'processStatusData(candidates) {\n    const statusCounts = {};\n    candidates.forEach(candidate => {\n        const status = candidate.status || \'Pending\';\n        statusCounts[status] = (statusCounts[status] || 0) + 1;\n    });\n    return statusCounts;\n}'),
        
        # Fix missing closing braces in processHRData
        (r'processHRData\(candidates\) \{[\s\S]*?return hrCounts;', 'processHRData(candidates) {\n    const hrCounts = {};\n    candidates.forEach(candidate => {\n        const hr = candidate.hr || \'Unknown HR\';\n        hrCounts[hr] = (hrCounts[hr] || 0) + 1;\n    });\n    return hrCounts;\n}'),
        
        # Fix missing closing braces in processDateData
        (r'processDateData\(candidates\) \{[\s\S]*?return dateCounts;', 'processDateData(candidates) {\n    const dateCounts = {};\n    candidates.forEach(candidate => {\n        const date = candidate.date || new Date().toISOString().split(\'T\')[0];\n        dateCounts[date] = (dateCounts[date] || 0) + 1;\n    });\n    return dateCounts;\n}'),
        
        # Fix missing closing braces in restoreManagerChartCanvases
        (r'restoreManagerChartCanvases\(\) \{[\s\S]*?if \(dateContainer && !dateContainer\.querySelector\(\'canvas\'\)\) \{[\s\S]*?innerHTML = \'<canvas id="managerDateChartCanvas"></canvas>\';', 'restoreManagerChartCanvases() {\n    const statusContainer = document.getElementById(\'managerStatusChart\');\n    const hrContainer = document.getElementById(\'managerHRChart\');\n    const dateContainer = document.getElementById(\'managerDateChart\');\n    if (statusContainer && !statusContainer.querySelector(\'canvas\')) {\n        statusContainer.innerHTML = \'<canvas id="managerStatusChartCanvas"></canvas>\';\n    }\n    if (hrContainer && !hrContainer.querySelector(\'canvas\')) {\n        hrContainer.innerHTML = \'<canvas id="managerHRChartCanvas"></canvas>\';\n    }\n    if (dateContainer && !dateContainer.querySelector(\'canvas\')) {\n        dateContainer.innerHTML = \'<canvas id="managerDateChartCanvas"></canvas>\';\n    }\n}'),
        
        # Fix missing closing braces in renderManagerHRChart
        (r'renderManagerHRChart\(data\) \{[\s\S]*?ticks: \{ stepSize: 1 \}[\s\S]*?}', 'renderManagerHRChart(data) {\n    const ctx = document.getElementById(\'managerHRChartCanvas\');\n    if (!ctx) return;\n    new Chart(ctx, {\n        type: \'bar\',\n        data: {\n            labels: Object.keys(data),\n            datasets: [{\n                label: \'Candidates\',\n                data: Object.values(data),\n                backgroundColor: \'rgba(16, 185, 129, 0.8)\',\n                borderColor: \'#10b981\',\n                borderWidth: 2,\n                borderRadius: 8\n            }]\n        },\n        options: {\n            responsive: true,\n            maintainAspectRatio: false,\n            plugins: {\n                legend: { display: false },\n                title: {\n                    display: true,\n                    text: \'Candidates by HR\',\n                    font: { size: 16, weight: \'bold\' }\n                }\n            },\n            scales: {\n                y: {\n                    beginAtZero: true,\n                    ticks: { stepSize: 1 }\n                }\n            }\n        }\n    });\n}'),
        
        # Fix missing closing braces in renderManagerDateChart
        (r'renderManagerDateChart\(data\) \{[\s\S]*?ticks: \{ stepSize: 1 \}[\s\S]*?}', 'renderManagerDateChart(data) {\n    const ctx = document.getElementById(\'managerDateChartCanvas\');\n    if (!ctx) return;\n    new Chart(ctx, {\n        type: \'line\',\n        data: {\n            labels: Object.keys(data),\n            datasets: [{\n                label: \'Candidates\',\n                data: Object.values(data),\n                borderColor: \'#8b5cf6\',\n                backgroundColor: \'rgba(139, 92, 246, 0.1)\',\n                borderWidth: 3,\n                fill: true,\n                tension: 0.4\n            }]\n        },\n        options: {\n            responsive: true,\n            maintainAspectRatio: false,\n            plugins: {\n                legend: { display: false },\n                title: {\n                    display: true,\n                    text: \'Candidate Addition Trend\',\n                    font: { size: 16, weight: \'bold\' }\n                }\n            },\n            scales: {\n                y: {\n                    beginAtZero: true,\n                    ticks: { stepSize: 1 }\n                }\n            }\n        }\n    });\n}'),
        
        # Fix missing closing braces in showManagerSampleData
        (r'showManagerSampleData\(\) \{[\s\S]*?updateManagerSummary\(sampleCandidates\);', 'showManagerSampleData() {\n    const sampleData = {\n        statusData: { \'Selected\': 2, \'Not Selected\': 1, \'Pending\': 1, \'Reassigned\': 0 },\n        hrData: { \'Monish\': 2, \'Ram\': 2 },\n        dateData: { \'2025-08-16\': 2, \'2025-08-17\': 1, \'2025-08-18\': 1 }\n    };\n    renderManagerCharts(sampleData.statusData, sampleData.hrData, sampleData.dateData);\n    const sampleCandidates = [\n        { status: \'Selected\' }, { status: \'Selected\' },\n        { status: \'Not Selected\' }, { status: \'Pending\' }\n    ];\n    updateManagerSummary(sampleCandidates);\n}'),
        
        # Fix missing closing braces in updateManagerSummary
        (r'updateManagerSummary\(candidates\) \{[\s\S]*?if \(dateContainer\) \{[\s\S]*?innerHTML = createManagerHTMLDateChart\(\);', 'updateManagerSummary(candidates) {\n    const statusCounts = processStatusData(candidates);\n    const hrCounts = processHRData(candidates);\n    const dateCounts = processDateData(candidates);\n    const hrContainer = document.getElementById(\'managerHRChart\');\n    const dateContainer = document.getElementById(\'managerDateChart\');\n    if (hrContainer) {\n        hrContainer.innerHTML = createManagerHTMLHRChart();\n    }\n    if (dateContainer) {\n        dateContainer.innerHTML = createManagerHTMLDateChart();\n    }\n}'),
        
        # Fix missing closing braces in createManagerHTMLHRChart
        (r'createManagerHTMLHRChart\(\) \{[\s\S]*?return html;', 'createManagerHTMLHRChart() {\n    const html = `<div class="text-center p-8 text-gray-500">\n        <i class="fas fa-chart-bar text-4xl mb-4"></i>\n        <p class="text-lg">HR Chart Data</p>\n        <p class="text-sm">Chart will be displayed here</p>\n    </div>`;\n    return html;\n}'),
        
        # Fix missing closing braces in createManagerHTMLDateChart
        (r'createManagerHTMLDateChart\(\) \{[\s\S]*?return html;', 'createManagerHTMLDateChart() {\n    const html = `<div class="text-center p-8 text-gray-500">\n        <i class="fas fa-chart-line text-4xl mb-4"></i>\n        <p class="text-lg">Date Chart Data</p>\n        <p class="text-sm">Chart will be displayed here</p>\n    </div>`;\n    return html;\n}'),
        
        # Fix missing closing braces in renderManagerCharts
        (r'renderManagerCharts\(statusData, hrData, dateData\) \{[\s\S]*?renderManagerDateChart\(dateData\);', 'renderManagerCharts(statusData, hrData, dateData) {\n    restoreManagerChartCanvases();\n    renderManagerStatusChart(statusData);\n    renderManagerHRChart(hrData);\n    renderManagerDateChart(dateData);\n}'),
        
        # Fix missing closing braces in renderManagerStatusChart
        (r'renderManagerStatusChart\(data\) \{[\s\S]*?font: \{ size: 16, weight: \'bold\' \}[\s\S]*?}', 'renderManagerStatusChart(data) {\n    const ctx = document.getElementById(\'managerStatusChartCanvas\');\n    if (!ctx) return;\n    new Chart(ctx, {\n        type: \'doughnut\',\n        data: {\n            labels: Object.keys(data),\n            datasets: [{\n                data: Object.values(data),\n                backgroundColor: [\n                    \'#10b981\', \'#ef4444\', \'#f59e0b\', \'#8b5cf6\'\n                ],\n                borderWidth: 2,\n                borderColor: \'#ffffff\'\n            }]\n        },\n        options: {\n            responsive: true,\n            maintainAspectRatio: false,\n            plugins: {\n                legend: {\n                    position: \'bottom\',\n                    labels: {\n                        font: { size: 12 },\n                        padding: 20\n                    }\n                },\n                title: {\n                    display: true,\n                    text: \'Candidate Status Distribution\',\n                    font: { size: 16, weight: \'bold\' }\n                }\n            }\n        }\n    });\n}'),
        
        # Fix missing closing braces in updateBulkActionBar
        (r'updateBulkActionBar\(\) \{[\s\S]*?bulkActionBar\.classList\.toggle\(\'hidden\', selected\.length === 0\);', 'updateBulkActionBar() {\n    const selected = document.querySelectorAll(\'.select-item:checked\');\n    const bulkActionBar = document.getElementById(\'bulk-action-bar\');\n    const selectedCount = document.getElementById(\'selected-count\');\n    if (selectedCount) {\n        selectedCount.textContent = `${selected.length} selected`;\n    }\n    if (bulkActionBar) {\n        bulkActionBar.classList.toggle(\'hidden\', selected.length === 0);\n    }\n}'),
        
        # Fix missing closing braces in updateSelectAllCheckbox
        (r'updateSelectAllCheckbox\(\) \{[\s\S]*?selectAllCheckbox\.indeterminate = true;[\s\S]*?}', 'updateSelectAllCheckbox() {\n    const selectAllCheckbox = document.getElementById(\'select-all\');\n    const selectItems = document.querySelectorAll(\'.select-item\');\n    const checkedItems = document.querySelectorAll(\'.select-item:checked\');\n    if (selectAllCheckbox) {\n        if (checkedItems.length === 0) {\n            selectAllCheckbox.checked = false;\n            selectAllCheckbox.indeterminate = false;\n        } else if (checkedItems.length === selectItems.length) {\n            selectAllCheckbox.checked = true;\n            selectAllCheckbox.indeterminate = false;\n        } else {\n            selectAllCheckbox.checked = false;\n            selectAllCheckbox.indeterminate = true;\n        }\n    }\n}'),
        
        # Fix missing closing braces in DOMContentLoaded
        (r'document\.addEventListener\(\'DOMContentLoaded\', function\(\) \{[\s\S]*?initializeManagerStarRatings\(\);', 'document.addEventListener(\'DOMContentLoaded\', function() {\n    initializeSelectMode();\n    initializeManagerStarRatings();\n});'),
        
        # Fix missing closing braces in fadeOut animation
        (r'const style = document\.createElement\(\'style\'\);[\s\S]*?document\.head\.appendChild\(style\);', 'const style = document.createElement(\'style\');\nstyle.textContent = `\n@keyframes fadeOut {\n    from {\n        opacity: 1;\n        transform: translateX(0);\n    }\n    to {\n        opacity: 0;\n        transform: translateX(-20px);\n    }\n}`;\ndocument.head.appendChild(style);'),
        
        # Fix missing closing braces in individual checkbox functionality
        (r'selectItems\.forEach\(cb => \{[\s\S]*?updateSelectAllCheckbox\(\);[\s\S]*?}\);', 'selectItems.forEach(cb => {\n        cb.addEventListener(\'change\', function() {\n            updateBulkActionBar();\n            updateSelectAllCheckbox();\n        });\n    });'),
    ]
    
    for pattern, replacement in fixes:
        content = re.sub(pattern, replacement, content, flags=re.DOTALL)
    
    with open('templates/manager/dashboard.html', 'w') as f:
        f.write(content)
    
    print("✅ Remaining manager dashboard issues fixed")

if __name__ == "__main__":
    fix_remaining_issues()
